
/**
* CompteCourant.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from banque.idl
* dimanche 5 décembre 2021 22 h 31 GMT+01:00
*/

public interface CompteCourant extends CompteCourantOperations, Compte, org.omg.CORBA.portable.IDLEntity 
{
} // interface CompteCourant
