
/**
* CompteCourantRemunereHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from banque.idl
* dimanche 5 décembre 2021 22 h 31 GMT+01:00
*/

public final class CompteCourantRemunereHolder implements org.omg.CORBA.portable.Streamable
{
  public CompteCourantRemunere value = null;

  public CompteCourantRemunereHolder ()
  {
  }

  public CompteCourantRemunereHolder (CompteCourantRemunere initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CompteCourantRemunereHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CompteCourantRemunereHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CompteCourantRemunereHelper.type ();
  }

}
