
/**
* CompteCourantOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from banque.idl
* dimanche 5 décembre 2021 22 h 31 GMT+01:00
*/

public interface CompteCourantOperations  extends CompteOperations
{
  boolean DecouvertAutorise ();
  void DecouvertAutorise (boolean newDecouvertAutorise);
} // interface CompteCourantOperations
