
/**
* CompteCourantOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from banque.idl
* mercredi 24 novembre 2021 11 h 10 GMT+01:00
*/

public interface CompteCourantOperations  extends CompteOperations
{
  boolean DecouvertAutorise ();
  void DecouvertAutorise (boolean newDecouvertAutorise);
} // interface CompteCourantOperations
