
/**
* CompteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from banque.idl
* mercredi 24 novembre 2021 11 h 10 GMT+01:00
*/

public interface CompteOperations 
{
  float lire_montant (org.omg.CORBA.FloatHolder solde);
  void crediter (float somme_credit, org.omg.CORBA.FloatHolder solde);
  void debiter (float somme_debit, org.omg.CORBA.FloatHolder solde);
} // interface CompteOperations
